/* 모든 데이터·세션은 이 페이지 안에서만 동작하는 디자인 시연용이다. */
(() => {
  const $ = s => document.querySelector(s);
  const icon = Art.icon;
  const query = new URLSearchParams(location.search);
  const state = { view:'home', night:false, art:query.get('art')!=='vector', overview:false, duration:25, startedAt:null, elapsed:0, lastSeconds:1500, island:'느티나무 섬', origin:null, visiting:false, recordSeconds:0, tab:'group', sound:false, audio:null, source:null, board:false, toastTimer:null };
  const names = {home:'광장 · 우리의 작은 섬',camp:'모닥불 · 집중 준비',session:'집중 중 · 곁에 있는 친구들',result:'세션 결과 · 함께 자란 시간',town:'마을회관 · 섬의 성장',board:'게시판 · 함께 정한 약속',cabin:'오두막 · 우리의 기록',harbor:'항구 · 다른 섬으로',tower:'전망대 · 다음 풍경',post:'우체국 · 다정한 안부'};
  const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const button = (label,action,cls='primary-button',ico='') => `<button class="${cls}" data-action="${action}">${ico?icon(ico):''}${label}</button>`;
  const goButton = (label,go,cls='primary-button',ico='') => `<button class="${cls}" data-go="${go}">${ico?icon(ico):''}${label}</button>`;
  const back = title => `<header class="scene-top"><div class="back-title"><button class="icon-button" data-go="home" aria-label="광장으로 돌아가기">${icon('back')}</button><h2 tabindex="-1">${title}</h2></div><span>${icon('leaf')}</span></header>`;
  const picture = (pose='idle',cls='') => `<img class="${cls}" src="assets/cat-${pose}.svg" alt="" width="40" height="40">`;
  function dock(){return `<nav class="dock" aria-label="섬의 건물">${[['town','town','회관'],['camp','fire','모닥불'],['board','board','게시판'],['cabin','cabin','오두막'],['tower','tower','전망대'],['post','post','우체국'],['harbor','harbor','항구']].map(([k,i,n])=>`<button class="dock-item ${['tower','post'].includes(k)?'locked':''}" data-go="${k}" aria-label="${n}${['tower','post'].includes(k)?' · 아직 열리지 않음':''}">${icon(i)}${['tower','post'].includes(k)?`<span class="lock-mini">${icon('lock')}</span>`:''}<span class="dock-label">${n}</span></button>`).join('')}</nav>`;}
  function worldArt(){return state.art&&!state.overview?`<img class="painted-world" src="assets/forest-day.png" alt="" width="852" height="1847">`:Art.world(state.night);}
  function home(){
    const spots=state.art&&!state.overview?[[48,32,'town'],[18,42,'board'],[68,55,'camp'],[22,65,'cabin'],[88,46,'tower'],[83,74,'post'],[55,84,'harbor']]:[[48,37,'town'],[24,46,'board'],[63,54,'camp'],[24,65,'cabin'],[90,48,'tower'],[84,73,'post'],[56,86,'harbor']];
    return `<section class="scene world ${state.night?'night':''} ${state.overview?'overview':''} ${state.art&&!state.overview?'painted':''}">${worldArt()}<div class="world-night-wash"></div><header class="world-header"><div class="island-title-row"><div><span class="eyebrow">우리의 작은 섬</span><button class="island-name" data-go="harbor">${esc(state.island)}${icon('down')}</button></div><button class="avatar-button" data-action="avatar" aria-label="내 고양이 보기">${picture('happy')}</button></div><div class="presence-line"><span class="live-dot"></span>오늘도 함께, 3명 집중 중</div><div class="resource-row"><span class="resource">${icon('leaf')}Lv. 3<span class="level-track"><i></i></span></span><span class="resource coin">${icon('coin')}128</span><div class="header-actions"><button class="icon-button" data-action="notice" aria-label="새 소식">${icon('bell')}<i class="notification-dot"></i></button></div></div></header>${spots.map(([x,y,k])=>`<button class="map-hit" data-go="${k}" style="left:${x}%;top:${y}%" aria-label="${names[k].split(' · ')[0]} 들어가기"></button>`).join('')}<div class="map-actions"><button class="live-bubble" data-go="camp"><span class="live-dot"></span>3명 집중 중</button></div>${!state.art?'<span class="my-position">나</span>':''}<div class="world-controls"><button data-action="zoom" aria-label="${state.overview?'가까이 보기':'섬 전체 보기'}" aria-pressed="${state.overview}">${icon('zoom')}</button><button data-action="night" aria-label="${state.night?'낮으로 바꾸기':'밤으로 바꾸기'}" aria-pressed="${state.night}">${icon(state.night?'sun':'moon')}</button></div>${state.visiting?'<div class="preview-banner">다른 섬을 구경하고 있어요 · 읽기 전용</div>':''}<div class="home-bottom"><div class="invitation"><div class="invite-copy"><div><h2>${state.visiting?'잠시 머물다 가도 좋아요':'우리, 같이 집중해볼까요?'}</h2><p>${state.visiting?'풍경을 둘러보고 내 섬으로 돌아가요':'모닥불 곁에 친구들이 기다리고 있어요'}</p></div><div class="friends-stack">${picture('focus')}${picture('focus')}${picture('happy')}</div></div>${state.visiting?button('내 섬으로 돌아가기','return','primary-button','harbor'):`<button class="primary-button" data-go="camp">${icon('fire')}같이 집중하기<span class="button-meta">${state.duration}분</span>${icon('arrow')}</button>`}</div>${dock()}</div></section>`;
  }
  function camp(active=false){return `<section class="scene camp ${active?'session':''} ${state.art?'painted-camp':''}">${state.art?'<img class="painted-camp-art" src="assets/forest-night.png" alt="" width="852" height="1847">':Art.camp()}<header class="scene-top">${active?`<span class="shield-pill">${icon('shield')}집중 공간</span>`:`<button class="icon-button" data-go="home" aria-label="광장으로 돌아가기">${icon('back')}</button>`}<h2 tabindex="-1">모닥불</h2><button class="icon-button" data-action="sound" aria-label="${state.sound?'숲 소리 끄기':'숲 소리 켜기'}" aria-pressed="${state.sound}">${icon(state.sound?'volume':'mute')}</button></header><div class="camp-copy">${active?`<h2>서로의 곁에서,<br>각자의 몰입으로.</h2><p>친구 3명과 함께 집중하고 있어요.</p><div class="timer" id="timer" aria-label="남은 집중 시간">${time(state.duration*60-state.elapsed)}</div><div class="timer-rule">${icon('leaf')}</div>`:`<div class="presence-line"><span class="live-dot"></span>친구 3명이 먼저 와 있어요</div><h2>잠깐, 세상은 내려놓고<br>우리 곁에 앉아요.</h2><p>각자의 할 일에 집중하는 동안<br>작은 섬도 함께 자랄 거예요.</p>`}</div><span class="camp-member-label">${active?'나':'내 자리'}</span>${!state.art?'<span class="camp-member-label other">모모 · 독서 중</span>':''}<div class="camp-bottom">${active?`<p class="session-bottom-note">화면을 내려놓아도, 우리는 함께예요.</p><p class="session-shield">${icon('shield')}집중 공간만 열려 있어요</p><div class="session-controls">${button(state.sound?'소리 끄기':'소리 켜기','sound','',state.sound?'volume':'mute')}${button('집중 마치기','finish','end-session','check')}</div><div class="session-progress"><i id="session-progress"></i></div>`:`<div class="duration-label"><span>얼마나 함께할까요?</span><span>집중 시간</span></div><div class="duration-options">${[25,50,90].map(n=>`<button data-duration="${n}" aria-pressed="${state.duration===n}">${n}분</button>`).join('')}</div>${button('이 자리에 앉아 시작하기','start','primary-button','fire')}<p class="fine-print">디자인 시연에서는 실제 앱 차단이 적용되지 않아요.</p>`}</div></section>`;}
  function time(sec){const s=Math.max(0,Math.floor(sec));return `${String(Math.floor(s/60)).padStart(2,'0')}<span>:</span>${String(s%60).padStart(2,'0')}`;}
  function result(){const mins=Math.floor(state.lastSeconds/60),secs=Math.floor(state.lastSeconds%60);return `<section class="scene paper-scene result"><header class="scene-top">${esc(state.origin||state.island)}에서 보낸 시간</header><div class="page-content"><div class="result-heading"><span class="success-label">${icon('check')}오늘도 한 걸음</span><h2 tabindex="-1">당신이 집중한 만큼,<br>우리 숲이 자랐어요.</h2><p>함께라서 조금 더 해낼 수 있었죠.</p></div><div class="result-art">${Art.vignette('cat')}</div><div class="receipt"><div class="receipt-top"><span>오늘의 집중 한 장</span>${icon('leaf')}</div><div class="receipt-time">${mins}<span>분</span>${secs?`${secs}<span>초</span>`:''}</div><div class="receipt-row"><span>나의 집중 기록</span><strong>+ ${mins}분 ${secs}초</strong></div><div class="receipt-row"><span>${esc(state.origin||state.island)}의 시간</span><strong>+ ${mins}분 ${secs}초</strong></div><div class="receipt-row"><span>함께한 친구</span><span>모모 · 두부 · 밤이</span></div></div><div class="result-growth">${icon('sprout')}<div><b>우리의 다음 풍경에 가까워졌어요.</b><span>모인 시간은 섬의 성장 기록에 남아요.</span></div></div>${goButton('우리 숲으로 돌아가기','home','primary-button','leaf')}${goButton('오늘의 기록 보기','cabin','text-button')}</div></section>`;}
  function town(){return `<section class="scene paper-scene">${back('마을회관')}<div class="page-content"><div class="page-illustration">${Art.building('town')}</div><div class="island-level"><span class="eyebrow">함께 키우는 섬</span><h3>${esc(state.island)}</h3><p>차곡차곡 쌓인 우리의 시간이 풍경이 돼요.</p></div><div class="subtle-card level-progress"><div class="progress-meta"><b>Lv. 3 · 작은 숲</b><span>다음 풍경까지</span></div><div class="progress-track" style="margin:12px 0"><i style="width:62%"></i></div><div class="progress-meta"><span>성장 진행도</span><span>62% · 시연값</span></div></div><h3 class="section-subtitle">섬에 찾아올 변화</h3><div class="unlock-row">${Art.building('cabin')}<div>우리의 기록을 담는 오두막<p>그룹과 나의 집중 기록</p></div><span class="tag">열림</span></div><div class="unlock-row">${Art.building('tower')}<div>더 멀리 바라보는 전망대<p>섬이 자라면 랭킹이 열려요</p></div><span class="tag">다음</span></div><div class="unlock-row">${Art.building('post')}<div>마음을 전하는 우체국<p>프리셋 편지와 콕찌르기</p></div></div><h3 class="section-subtitle">우리 섬 관리</h3>${button('섬 이름 바꾸기','rename','secondary-button','settings')}<p class="fine-print" style="margin-top:12px">시연은 그룹장 화면입니다. 성장 기준·보상 수치는 추후 확정됩니다.</p></div></section>`;}
  function board(){return `<section class="scene paper-scene">${back('게시판')}<div class="page-content"><h2 class="section-title">함께 정한 작은 약속</h2><p class="page-intro">혼자서는 어려워도, 우리라면.</p><div class="notice-card"><small>${icon('flag')}섬의 공지 · 모모</small><h3>오늘도 각자의 속도로.</h3><p>오후에는 모닥불에서 만나요.<br>늦게 와도 괜찮아요. 자리는 늘 있으니까.</p></div><h3 class="section-subtitle">오늘의 퀘스트 <small>3개의 약속</small></h3><article class="quest-card"><div class="quest-head"><span class="quest-icon">${icon('clock')}</span><div><h3>나를 위한 한 시간</h3><p>오늘 60분 집중하기</p></div></div><div class="progress-track"><i style="width:${Math.min(100,(35+state.recordSeconds/60)/60*100)}%"></i></div><div class="progress-meta"><span>${Math.floor(35+state.recordSeconds/60)} / 60분</span><span>매일 반복</span></div>${goButton('모닥불에서 이어하기','camp','secondary-button','fire')}</article><article class="quest-card"><div class="quest-head"><span class="quest-icon">${icon('shield')}</span><div><h3>폰보다 나에게 더 가까이</h3><p>하루 폰 사용 2시간 이내</p></div></div><div class="progress-meta" style="margin-top:16px"><span>오늘 48분 사용</span><span>목표 안에서 잘하고 있어요</span></div></article><article class="quest-card"><div class="quest-head"><span class="quest-icon">${icon('book')}</span><div><h3>오늘 배운 한 가지</h3><p>자료 공유 · 이미지, PDF, 텍스트</p></div></div>${button('자료 공유 살펴보기','share','secondary-button','plus')}</article></div></section>`;}
  function cabin(){const personal=state.tab==='me';let data=personal?[42,68,52,82,60,18,0]:[68,91,59,115,90,25,0];return `<section class="scene paper-scene">${back('오두막')}<div class="page-content"><h2 class="section-title">시간이 남긴 작은 숲</h2><p class="page-intro">눈에 보이지 않던 노력이, 여기 모여 있어요.</p><div class="tabs" role="tablist" aria-label="집중 기록 범위"><button role="tab" id="tab-group" aria-selected="${!personal}" aria-controls="stats-panel" tabindex="${personal?-1:0}" data-tab="group">우리 섬</button><button role="tab" id="tab-me" aria-selected="${personal}" aria-controls="stats-panel" tabindex="${personal?0:-1}" data-tab="me">나의 기록</button></div><div id="stats-panel" role="tabpanel" aria-labelledby="tab-${state.tab}"><span class="stat-label">이번 주 함께 쌓은 시간</span><div class="big-stat">${personal?'8':'32'}<span> 시간 </span>${personal?'35':'20'}<span> 분</span></div><div class="weekly-chart" role="img" aria-label="이번 주 월요일부터 일요일까지의 집중 시간 예시">${data.map((v,i)=>`<div class="chart-column ${i===5?'current':''}"><div class="bar" style="height:${v}px"></div><span>${['월','화','수','목','금','토','일'][i]}</span></div>`).join('')}</div><div class="subtle-card" style="margin-top:22px"><span class="stat-label">${personal?'오늘 나의 집중':'오늘 우리 섬의 집중'}</span><div class="big-stat" style="font-size:28px">${personal?'35':'140'}<span>분${state.recordSeconds?` + ${Math.floor(state.recordSeconds/60)}분 ${state.recordSeconds%60}초`:''}</span></div></div></div><h3 class="section-subtitle">함께 있는 친구들 <small>5명</small></h3>${[['모모','독서 · 집중 중','1시간 12분'],['두부','자격증 공부 · 집중 중','58분'],['밤이','포트폴리오 · 집중 중','35분'],['나','오늘의 작은 성취','35분'],['소금','잠시 쉬는 중','20분']].map(([n,s,t],i)=>`<div class="member-row">${picture(i<3?'focus':'idle')}<div><p>${n}</p><small>${s}</small></div><span class="member-time">${t}</span></div>`).join('')}</div></section>`;}
  function harbor(){return `<section class="scene paper-scene">${back('항구')}<div class="page-content"><h2 class="section-title">오늘은 어느 숲에 머물까요?</h2><p class="page-intro">어디서 집중하든, 그 섬에 시간이 남아요.</p><div class="harbor-art">${Art.building('harbor')}</div><h3 class="section-subtitle">내가 함께하는 섬 <small>2곳</small></h3>${['느티나무 섬','새벽의 서재'].map((name,i)=>`<button class="island-option ${state.island===name&&!state.visiting?'selected':''}" data-island="${name}">${icon(i?'book':'sprout')}<span><b>${name}</b><small>Lv. ${i?2:3} · ${i?4:5}명의 친구들</small></span><span class="option-end">${state.island===name&&!state.visiting?'머무는 중':icon('arrow')}</span></button>`).join('')}<h3 class="section-subtitle">새로운 풍경</h3><button class="island-option" data-action="visit">${icon('sun')}<span><b>햇살 머무는 섬</b><small>잠깐 산책하기 · 읽기 전용</small></span><span class="option-end">${icon('arrow')}</span></button><p class="harbor-note">${icon('leaf')}집중 시간은 세션을 시작한 섬에 쌓여요.<br>섬을 옮겨도 이전 기록은 그대로 남아요.</p></div></section>`;}
  function locked(which){const tower=which==='tower';return `<section class="scene paper-scene">${back(tower?'전망대':'우체국')}<div class="page-content"><div class="empty-state">${Art.building(which)}<h3>조금 더 자라면, 만나요.</h3><p>${tower?'우리 섬과 다른 섬의 집중 기록을<br>더 멀리 바라볼 수 있는 곳이에요.':'친구에게 다정한 안부를 전하는 곳이에요.<br>준비된 문구로 마음을 나누게 돼요.'}</p><div class="subtle-card" style="margin-top:24px;font-size:13px">${icon('lock')} 섬의 성장에 따라 열리는 건물</div>${goButton('우리 섬의 성장 보기','town','primary-button','sprout')}</div></div></section>`;}
  function render(focus=true){const views={home,camp:()=>camp(false),session:()=>camp(true),result,town,board,cabin,harbor,tower:()=>locked('tower'),post:()=>locked('post')};$('#view').innerHTML=(views[state.view]||home)();$('#view-caption').textContent=names[state.view];document.querySelectorAll('.story-nav [data-go]').forEach(el=>{if(el.dataset.go===state.view||(state.view==='session'&&el.dataset.go==='camp'))el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});$('#day').setAttribute('aria-pressed',!state.night);$('#night').setAttribute('aria-pressed',state.night);if(focus)$('#view h2')?.focus({preventScroll:true});updateTimer();}
  function navigate(view){if(state.startedAt&&view!=='session'){toast('지금은 집중 중이에요. 집중을 마친 뒤 둘러볼 수 있어요.');return;}if(state.visiting&&['camp','town','board','cabin','tower','post'].includes(view)){toast('구경 중인 섬에서는 건물을 이용할 수 없어요. 내 섬으로 돌아가주세요.');return;}state.view=view;render();}
  function toast(message){clearTimeout(state.toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;state.toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
  function modal(title,body,actions=''){$('#dialog-content').innerHTML=`<div class="dialog-header"><h2 id="dialog-title">${title}</h2><button class="icon-button" data-action="close" aria-label="닫기">${icon('close')}</button></div>${body}${actions?`<div class="dialog-actions">${actions}</div>`:''}`;$('#dialog').showModal();}
  function updateTimer(){if(!state.startedAt)return;state.elapsed=Math.max(0,Math.floor((Date.now()-state.startedAt)/1000));const target=$('#timer');if(target)target.innerHTML=time(state.duration*60-state.elapsed);const progress=$('#session-progress');if(progress)progress.style.width=`${Math.min(100,state.elapsed/(state.duration*60)*100)}%`;if(state.elapsed>=state.duration*60)finish();}
  function finish(){if(!state.startedAt)return;state.lastSeconds=Math.max(1,Math.floor((Date.now()-state.startedAt)/1000));state.recordSeconds+=state.lastSeconds;state.startedAt=null;stopSound();$('#dialog').close();state.view='result';render();}
  function stopSound(){state.source?.stop();state.source=null;state.audio?.close();state.audio=null;state.sound=false;}
  async function sound(){if(state.sound){stopSound();render(false);return;}try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)throw new Error('unavailable');state.audio=new Ctx();await state.audio.resume();const buffer=state.audio.createBuffer(1,state.audio.sampleRate*3,state.audio.sampleRate);const values=buffer.getChannelData(0);let last=0;for(let i=0;i<values.length;i++){last=(last+(Math.random()*2-1)*.02)/1.02;values[i]=last*3.5;}const source=state.audio.createBufferSource();source.buffer=buffer;source.loop=true;const gain=state.audio.createGain();gain.gain.value=.14;const filter=state.audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=850;source.connect(filter).connect(gain).connect(state.audio.destination);source.start();state.source=source;state.sound=true;render(false);}catch{stopSound();toast('소리를 재생하지 못했어요. 브라우저의 소리 권한을 확인해주세요.');}}
  const actions={
    start(){state.origin=state.island;state.startedAt=Date.now();state.elapsed=0;state.view='session';render();},
    finish(){modal('여기까지 집중할까요?','<p class="dialog-copy">지금까지 집중한 시간은 그대로 기록돼요.<br>준비되면 언제든 다시 곁에 앉아요.</p>',button('조금 더 집중하기','close','secondary-button')+button('집중 마치기','confirm-finish'));},
    'confirm-finish':finish, close:()=>$('#dialog').close(),sound,
    zoom(){state.overview=!state.overview;render(false);},night(){state.night=!state.night;render(false);},
    notice(){modal('숲에 도착한 소식','<div class="notice-card"><small>모모 · 섬의 공지</small><h3>오늘도 각자의 속도로.</h3><p>오후에는 모닥불에서 만나요. 늦게 와도 괜찮아요.</p></div>',goButton('게시판으로 가기','board'));},
    avatar(){modal('오늘도 반가워요',`<div style="height:150px">${Art.vignette('cat')}</div><p class="dialog-copy">내가 머무는 곳에 고양이도 함께해요.<br>집중을 시작하면 책을 펼치고 자리에 앉아요.</p>`,button('숲으로 돌아가기','close'));},
    rename(){modal('섬의 이름',`<label class="form-label" for="island-name">함께 부를 이름</label><input id="island-name" maxlength="16" value="${esc(state.island)}" aria-describedby="name-error"><p class="form-error" id="name-error"></p><p class="fine-print">이 시안에서만 변경되며 서버에 저장되지 않아요.</p>`,button('이 이름으로 부르기','save-name'));},
    'save-name'(){const input=$('#island-name'),value=input.value.trim();if(value.length<2){input.setAttribute('aria-invalid','true');$('#name-error').textContent='섬 이름을 두 글자 이상 적어주세요.';input.focus();return;}state.island=value;$('#dialog').close();render();},
    share(){modal('오늘 배운 한 가지','<p class="dialog-copy">공유할 자료의 형식을 골라보는 시연입니다. 실제 업로드와 저장은 연결되지 않았어요.</p><div class="preset-list"><button data-action="share-info">이미지로 공유하기</button><button data-action="share-info">PDF로 공유하기</button><button data-action="share-info">글로 남기기</button></div>');},
    'share-info'(){modal('자료 공유 준비 중','<p class="dialog-copy">이 디자인 시안에는 파일 업로드가 연결되지 않았어요. 실제 앱에서는 작성자 표시, 댓글과 신고 기능이 함께 제공됩니다.</p>',button('확인','close'));},
    visit(){state.visiting=true;state.island='햇살 머무는 섬';state.view='home';render();},
    return(){state.visiting=false;state.island='느티나무 섬';state.view='home';render();},
    art(){state.art=!state.art;state.overview=false;$('#art-mode').setAttribute('aria-pressed',state.art);$('#art-mode').innerHTML=icon('grid')+(state.art?'SVG 구조 비교':'아트 시안 보기');render(false);}
  };
  document.addEventListener('click',event=>{const el=event.target.closest('button');if(!el||el.disabled)return;if(el.dataset.go){$('#dialog').close();navigate(el.dataset.go);}else if(el.dataset.action){if(state.startedAt&&!['finish','confirm-finish','close','sound'].includes(el.dataset.action)){toast('집중 중에는 집중 공간만 이용할 수 있어요.');return;}actions[el.dataset.action]?.();}else if(el.dataset.duration){state.duration=Number(el.dataset.duration);render(false);}else if(el.dataset.tab){state.tab=el.dataset.tab;render(false);$(`#tab-${state.tab}`).focus({preventScroll:true});}else if(el.dataset.island){state.island=el.dataset.island;state.visiting=false;navigate('home');}});
  document.addEventListener('keydown',event=>{if(event.target.matches('[role=tab]')&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();state.tab=event.key==='Home'?'group':event.key==='End'?'me':state.tab==='me'?'group':'me';render(false);$(`#tab-${state.tab}`).focus({preventScroll:true});}});
  $('#dialog').addEventListener('click',event=>{if(event.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('#dialog').close();}});
  $('#day').onclick=()=>{if(state.startedAt)return toast('집중을 마친 뒤 바꿀 수 있어요.');state.night=false;render(false);};$('#night').onclick=()=>{if(state.startedAt)return toast('집중을 마친 뒤 바꿀 수 있어요.');state.night=true;render(false);};
  $('#reset').onclick=()=>{if(state.startedAt){actions.finish();return;}stopSound();state.view='home';state.island='느티나무 섬';state.visiting=false;state.overview=false;state.lastSeconds=1500;state.origin=null;render();};
  $('#board-toggle').onclick=()=>{if(state.startedAt)return toast('집중을 마친 뒤 둘러볼 수 있어요.');state.board=!state.board;$('#screen-board').hidden=!state.board;$('.studio').hidden=state.board;$('#board-toggle').setAttribute('aria-pressed',state.board);$('#board-toggle').innerHTML=icon('grid')+(state.board?'앱으로 돌아가기':'화면 모아보기');if(state.board&&!$('#board-grid').children.length){$('#board-grid').innerHTML=['home','camp','session','result','town','board','cabin','harbor','tower'].map(k=>`<article class="board-item"><h3>${names[k]}</h3><iframe loading="lazy" title="${names[k]}" src="?embed=1&screen=${k}&art=${state.art?'painted':'vector'}"></iframe></article>`).join('');}};
  $('#intro-art').innerHTML=Art.vignette();$('#mini-art').innerHTML=Art.vignette('camp');document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));
  const artControl=document.createElement('button');artControl.id='art-mode';artControl.className='quiet-button art-mode';artControl.dataset.action='art';artControl.setAttribute('aria-pressed',state.art);artControl.innerHTML=icon('grid')+(state.art?'SVG 구조 비교':'아트 시안 보기');$('.stage-caption').after(artControl);
  if(query.has('embed'))document.body.classList.add('embed');if(query.has('screen')&&names[query.get('screen')])state.view=query.get('screen');
  if(state.view==='session'){state.startedAt=Date.now()-22000;state.origin=state.island;}
  setInterval(updateTimer,1000);document.addEventListener('visibilitychange',updateTimer);window.addEventListener('pagehide',stopSound);render(false);
})();
