/* 건물별 정보 구조. 지도·세션 상태는 village.js가 소유하고 이 모듈은 화면만 만든다. */
(() => {
  'use strict';
  const esc=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icon=name=>Art.icon(name);
  const presets=['오늘도 함께해서 좋았어!','네 속도로, 천천히 해도 괜찮아.','우리 내일도 여기서 만나.'];
  const members=[['모모','독서','집중 중'],['두부','자격증 공부','집중 중'],['밤이','포트폴리오','집중 중'],['소금','잠시 쉬는 중','휴식'],['나','나의 시간','준비 중']];
  const meta={town:['우리 섬의 성장','sprout'],camp:['곁에 앉아, 각자의 집중','fire'],board:['함께 정한 작은 약속','board'],cabin:['시간이 남긴 우리의 기록','chart'],tower:['함께 쌓은 시간의 높이','tower'],post:['다정한 안부가 머무는 곳','post'],harbor:['다른 섬으로 떠나는 길','harbor'],result:['오늘도 한 걸음','check']};
  const button=(label,attrs,kind='primary',glyph='arrow')=>`<button class="${kind}" ${attrs}><span>${label}</span>${glyph?icon(glyph):''}</button>`;
  const action=(label,key,kind='primary',glyph='arrow')=>button(label,`data-action="${key}"`,kind,glyph);
  const select=(label,key,kind='primary',glyph='arrow')=>button(label,`data-select="${key}"`,kind,glyph);
  const note=text=>`<p class="panel-footnote">${text}</p>`;
  const intro=(title,copy='',extra='')=>`<div class="building-intro ${extra}"><h3>${title}</h3>${copy?`<p>${copy}</p>`:''}</div>`;
  function tabs(scope,items,value){return `<div class="building-tabs ${scope==='record'?'record-tabs':''}" role="tablist" aria-label="${{board:'게시판 내용',record:'기록 범위',harbor:'섬 탐색',ranking:'랭킹 범위'}[scope]}">${items.map(([key,label])=>`<button role="tab" id="${scope}-tab-${key}" ${scope==='record'?`data-tab="${key}"`:`data-panel-tab="${scope}" data-value="${key}"`} aria-selected="${key===value}" aria-controls="${scope}-panel" tabindex="${key===value?0:-1}">${label}</button>`).join('')}</div>`;}
  const tabpanel=(scope,value,content)=>`<div id="${scope}-panel" role="tabpanel" aria-labelledby="${scope}-tab-${value}">${content}</div>`;
  const avatar=(index=0)=>`<span class="friend-portrait portrait-${index}" aria-hidden="true"><img src="assets/momo-walk-front.png" alt=""></span>`;
  const progress=(value,label)=>`<div class="growth-progress" role="progressbar" aria-label="${label}" aria-valuenow="${Math.min(100,Math.round(value))}" aria-valuemin="0" aria-valuemax="100"><span style="width:${Math.min(100,value)}%"></span></div>`;
  const formatTime=minutes=>`${Math.floor(minutes/60)}시간 ${Math.floor(minutes%60)}분`;
  function timeMarkup(minutes){const h=Math.floor(minutes/60),m=Math.floor(minutes%60);return `${h?`<strong>${h}</strong><span>시간</span>`:''}<strong>${m}</strong><span>분</span>`;}
  function friendRows(count=5){return `<div class="friend-list">${members.slice(0,count).map(([name,task,status],i)=>`<div class="friend-row">${avatar(i)}<span class="friend-info"><b>${name}</b><small>${task}</small></span><span class="friend-state ${i<3?'is-focusing':''}">${i<3?'<i class="live-dot"></i>':''}${status}</span></div>`).join('')}</div>`;}
  function camp(state){if(window.GachisupActivities)return GachisupActivities.panel(state);return {
    body:`<div class="focus-lead">${intro('잠깐, 나에게<br>집중할 시간','모닥불 곁에서, 각자의 할 일을 시작해요.','centered')}<div class="focus-duration" aria-live="polite"><svg viewBox="0 0 200 200" aria-hidden="true"><circle class="duration-track" cx="100" cy="100" r="88"/><circle class="duration-arc" cx="100" cy="100" r="88" pathLength="100" stroke-dasharray="${state.duration/90*85+15} 100"/></svg><div class="duration-value">${icon('fire')}<span><strong>${state.duration}</strong><small>분</small></span><em>나에게 머무는 시간</em></div></div></div><div class="duration-options" role="group" aria-label="집중 시간">${[25,50,90].map((n,i)=>`<button id="duration-${n}" data-duration="${n}" aria-pressed="${state.duration===n}"><b>${n}<small>분</small></b><span>${['가볍게 시작','깊이 몰입','오래 머물기'][i]}</span></button>`).join('')}</div><div class="camp-company" role="group" aria-label="모모, 두부, 밤이가 집중 중"><div class="friend-stack">${[0,1,2].map(avatar).join('')}<span class="company-dot"><i class="live-dot"></i>지금 함께</span></div><p><b>모모, 두부, 밤이</b>가 집중하고 있어요.<br>곁에 앉아도 괜찮아요.</p></div><p class="focus-policy">${icon('lock')}집중하는 동안에는 이 모닥불만 열려요.</p>`,
    footer:action(`${state.duration}분 함께 집중하기`,'start','primary','fire')+note('디자인 시연 · 실제 앱 차단 미연결')
  };}
  function town(state){const island=state.islands.find(i=>i.name===state.island)||state.islands[0];return {
    body:`${intro(esc(state.island),'각자의 시간이 모여, 우리 섬이 자라요.')}<div class="island-growth"><div class="level-display"><small>우리 섬의 지금</small><div><span>Lv.</span><strong>${island.level}</strong>${icon('sprout')}</div><p>함께 자라는 섬</p></div><div class="level-progress"><span>다음 풍경까지</span><strong>62<small>%</small></strong>${progress(62,'다음 풍경까지의 예시 성장률')}<small>성장률 시연값</small></div></div><h4 class="building-section-title">우리 섬의 열린 공간</h4><div class="growth-trail">${[['cabin','오두막','열려 있어요'],['tower','전망대','열려 있어요'],['post','우체국','열려 있어요']].map(([key,name,status],i)=>`<button class="growth-stop ${'is-open'}" data-select="${key}" aria-label="${name} · ${status}"><span class="growth-symbol">${icon(key)}<i>${icon('check')}</i></span><b>${name}</b><small>${status}</small></button>`).join('')}</div><section class="island-promise"><span class="section-kicker">우리 섬의 약속</span><h4>서로의 속도를 존중해요.</h4><p>늦게 와도, 잠시 쉬어 가도 괜찮아요.<br>오늘도 각자의 시간을 함께 쌓아요.</p></section><button class="building-link-row" data-action="members">${icon('people')}<span><b>함께하는 친구</b><small>모모와 ${island.members-1}명의 이웃</small></span><strong>${island.members}명</strong>${icon('arrow')}</button><p class="building-caption">레벨·해금 기준과 보상 단가는 미확정입니다.</p>`,
    footer:action('섬 이름 바꾸기','rename','primary','settings')+note('그룹장 설정 · 이 브라우저에 저장됩니다')
  };}
  function board(state){const value=state.boardTab||'quests',minutes=Math.floor(35+state.recordSeconds/60),pct=Math.min(100,minutes/60*100);const memo=`<article class="pinned-notice"><span class="notice-pin" aria-hidden="true"></span><div class="notice-byline">${avatar(0)}<span>모모 <small>그룹장 · 예시 공지</small></span></div><h3>오늘도 각자의 속도로.</h3><p>늦게 와도 괜찮아요.<br>모닥불 곁에는 늘 자리가 있으니까.</p></article>`;
    const quests=`<h4 class="building-section-title">오늘의 작은 약속 <span>3가지</span></h4><div class="quest-list"><button class="quest-item" data-action="quest-focus"><span class="quest-icon">${icon('clock')}</span><span class="quest-main"><b>나를 위한 한 시간</b><small>오늘 60분 집중하기</small>${progress(pct,'집중 목표 진행률')}<span class="quest-progress-label">${minutes} / 60분 <em>${Math.round(pct)}%</em></span></span>${icon('arrow')}</button><button class="quest-item" data-action="quest-phone"><span class="quest-icon">${icon('shield')}</span><span class="quest-main"><b>폰보다 나에게 가까이</b><small>오늘 48분 · 목표 2시간 이내</small><span class="quest-state">지금까지 잘 지키고 있어요</span></span>${icon('arrow')}</button><button class="quest-item" data-action="share"><span class="quest-icon">${icon('book')}</span><span class="quest-main"><b>오늘 배운 한 가지</b><small>이미지 · PDF · 텍스트로 자료 공유</small></span>${icon('arrow')}</button></div>`;
    return {body:tabs('board',[['quests','오늘의 약속'],['notice','공지']],value)+tabpanel('board',value,memo+(value==='quests'?quests:`<div class="notice-afterword">${icon('leaf')}<p>좋은 집중은 혼자 해도,<br>함께한다는 마음은 남으니까.</p></div><p class="building-caption">공지와 퀘스트는 예시입니다. 게시·댓글 서버는 아직 연결되지 않았어요.</p>`)),footer:select('모닥불에서 이어하기','camp','primary','fire')+note('예시 공지·퀘스트 · 새로고침하면 시연이 초기화돼요')};
  }
  function cabin(state){const island=state.islands.find(i=>i.name===state.island)||state.islands[0],seconds=state.recordTab==='me'?state.recordSeconds:(state.islandSeconds[island.id]||0);const me=state.recordTab==='me',data=me?[20,40,15,60,25,30,35]:[80,110,90,170,100,70,140];data[6]+=Math.floor(seconds/60);const day=state.recordDay??6,total=data.reduce((a,b)=>a+b,0),max=Math.max(180,...data),dates=data.map((_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return {label:i===6?'오늘':['일','월','화','수','목','금','토'][d.getDay()],full:`${d.getMonth()+1}월 ${d.getDate()}일`};});
    const chart=`<div class="record-headline"><span>오늘 ${me?'내가':'함께'} 모은 시간</span><div class="record-number">${timeMarkup(data[6])}</div></div><div class="chart-heading"><span>최근 7일</span><output id="record-day-value" aria-live="polite">${dates[day].full} · <b>${data[day]}분</b></output></div><div class="record-chart" role="group" aria-label="날짜를 눌러 집중 시간 확인">${data.map((n,i)=>`<button id="record-day-${i}" class="record-bar ${i===6?'is-today':''}" data-record-day="${i}" aria-label="${dates[i].full} ${n}분" aria-pressed="${i===day}"><span class="bar-column"><i style="height:${Math.max(3,n/max*100)}%"></i></span><span class="bar-day">${dates[i].label}</span></button>`).join('')}</div><div class="record-summary"><div>${icon('clock')}<span>최근 7일<strong>${formatTime(total)}</strong></span></div><div>${icon(me?'check':'people')}<span>${me?'집중한 날':'함께한 친구'}<strong>${me?'7일':island.members+'명'}</strong></span></div></div>${me?`<div class="personal-note">${icon('sprout')}<p>작은 시간도 모이면 숲이 돼요.<br>오늘 쌓은 ${data[6]}분도 소중한 한 걸음이에요.</p></div>`:`<h4 class="building-section-title">같은 섬에 있는 친구들</h4>${friendRows(island.members)}`}`;
    return {body:tabs('record',[['group','우리 섬'],['me','나의 기록']],state.recordTab)+tabpanel('record',state.recordTab,chart),footer:select('모닥불에서 시간 쌓기','camp','primary','fire')+note('예시 기록 · 현재 세션은 종료 후 반영됩니다')};
  }
  function harbor(state){const value=state.harborTab||'mine',selected=state.destination||null;const islands=state.islands;
    const mine=`<div class="island-options" role="group" aria-label="이동할 섬 선택">${islands.map((island,i)=>{const current=island.name===state.island;return `<button class="island-destination ${current?'is-current':''}" id="destination-${island.id}" data-destination="${island.id}" aria-pressed="${selected===island.id}" ${current?'aria-disabled="true"':''}><span class="destination-icon">${icon(i?'book':'flag')}</span><span><b>${esc(island.name)}</b><small>Lv. ${island.level} · 친구 ${island.members}명</small></span><span class="destination-state">${current?'머무는 중':selected===island.id?icon('check'):icon('arrow')}</span></button>`;}).join('')}</div><button class="explore-invitation" data-panel-tab="harbor" data-value="explore"><span>${icon('harbor')}</span><span><small>새로운 풍경이 궁금하다면</small><b>다른 섬 구경하기 ${icon('arrow')}</b></span></button>`;
    const explore=`<div class="explore-place"><span class="explore-sun">${icon('sun')}</span><span class="section-kicker">잠시, 다른 섬의 바람을</span><h4>햇살 머무는 섬</h4><p>누군가의 하루가 자라는 곳을<br>천천히 둘러보세요.</p><div class="voyage-route" aria-hidden="true">${icon('sprout')}<i></i>${icon('harbor')}</div></div><p class="focus-policy">${icon('shield')}다른 섬은 읽기 전용으로 구경해요.</p>`;
    const dest=islands.find(i=>i.id===selected),canTravel=dest&&dest.name!==state.island;
    return {body:intro('오늘은, 어느 섬에<br>머물까요?','집중한 시간은 시작한 섬에 남아요.')+tabs('harbor',[['mine','내가 머무는 섬'],['explore','구경하기']],value)+tabpanel('harbor',value,value==='mine'?mine:explore),footer:(value==='mine'?button(canTravel?'이 섬으로 이동하기':'이동할 섬을 골라주세요',`data-action="travel" ${canTravel?'':'disabled'}`,'primary','harbor'):action('햇살 머무는 섬 구경하기','visit','primary','harbor'))+note('프로토타입의 섬은 같은 마을 원화를 사용합니다')};
  }
  function tower(state){const value=state.rankingTab||'group',rows=value==='group'?[['모모','2시간 10분'],['두부','1시간 45분'],['밤이','1시간 20분']]:[['느티나무 섬','12시간 40분'],['새벽의 서재','10시간 25분'],['햇살 머무는 섬','8시간 15분']];return {
    body:`<div class="locked-feature"><div>${intro('조금 더 자라면,<br>더 멀리 보여요.')}<span class="locked-status">${icon('lock')}아직 열리지 않은 건물</span></div><div class="lookout-emblem" aria-hidden="true">${icon('tower')}<i></i>${icon('leaf')}</div></div>${tabs('ranking',[['group','우리 섬'],['islands','섬과 섬']],value)}${tabpanel('ranking',value,`<div class="preview-heading"><span>랭킹 화면 미리보기</span><small>예시</small></div><p class="building-caption">함께 쌓은 주간 집중 기록을 볼 수 있어요.</p><ol class="ranking-preview">${rows.map(([name,time],i)=>`<li><span class="ranking-number">0${i+1}</span><b>${esc(name)}</b><span>${time}</span></li>`).join('')}</ol>`)}<p class="unlock-note">순위보다 중요한 건, 함께 쌓는 시간.<br>섬이 성장하면 이곳에서 만나요.</p>`,
    footer:select('마을의 성장 살펴보기','town','primary','sprout')+note('열리는 레벨은 미확정 · 순위는 예시입니다')
  };}
  function post(state){const chosen=state.letterPreset??0;return {
    body:`${intro('짧은 한마디도,<br>오래 남으니까.','','centered')}<div class="letter-scene" aria-hidden="true"><div class="letter-glow"></div><div class="letter-envelope"><span class="envelope-flap"></span><span class="envelope-seal">${icon('sprout')}</span></div></div><div class="post-lock"><span class="locked-status">${icon('lock')}아직 열리지 않은 건물</span><p>지금은 편지를 보낼 수 없어요.<br>조금 더 마을이 자라면 열릴 거예요.</p></div><h4 class="building-section-title">이런 마음을 보낼 수 있어요</h4><div class="letter-presets" role="group" aria-label="편지 문구 미리보기">${presets.map((p,i)=>`<button id="letter-${i}" data-letter="${i}" aria-pressed="${chosen===i}">${p}${chosen===i?icon('check'):''}</button>`).join('')}</div><p class="letter-preview" aria-live="polite">${icon('post')}<span>“${presets[chosen]}”</span></p>`,
    footer:select('마을의 성장 살펴보기','town','primary','sprout')+note('프리셋 미리보기 · 실제 편지는 전송되지 않습니다')
  };}
  function result(state){if(state.lastKind==='rest'){const m=Math.floor(state.lastSeconds/60),s=state.lastSeconds%60;return {title:'잘 쉬고 돌아왔어요',body:`<div class="session-receipt"><div class="receipt-seal">${icon('harbor')}</div>${intro('잠깐의 여유도<br>소중한 시간이니까.','다시 시작할 준비가 되면, 천천히.','centered')}<div class="receipt-number"><strong>${m}</strong><span>분</span><strong>${s}</strong><span>초</span></div><p class="building-caption">휴식 기록에만 남겼어요.<br>집중 시간·순위·퀘스트에는 더하지 않아요.</p></div>${select('오두막에서 기록 보기','cabin','secondary','chart')}`,footer:action('마을로 돌아가기','close-panel')+note('휴식 기록은 이 브라우저에 저장됩니다')};}const m=Math.floor(state.lastSeconds/60),s=state.lastSeconds%60;return {body:`<div class="session-receipt"><div class="receipt-seal">${icon('check')}</div>${intro('오늘의 시간이<br>우리 섬에 남았어요.','잠깐의 집중도, 소중한 한 걸음.','centered')}<div class="receipt-number"><strong>${m}</strong><span>분</span><strong>${s}</strong><span>초</span></div><div class="receipt-rule"></div><div class="receipt-row"><span>나의 기록</span><b>+ ${m}분 ${s}초</b></div><div class="receipt-row"><span>${esc(state.lastOrigin||state.island)}</span><b>같은 시간 함께 적립</b></div><p class="building-caption">집중 시간은 시작한 섬에 남겨두었어요.</p></div>${select('오두막에서 기록 보기','cabin','secondary','chart')}`,footer:action('마을로 돌아가기','close-panel')+note('집중 기록은 이 브라우저에 저장됩니다')};}
  function visit(state,key,buildings){return {body:`<div class="visiting-content"><div class="visit-emblem">${icon(meta[key][1])}</div><span class="section-kicker">${esc(state.island)}에 방문 중</span>${intro(`${buildings[key].name}에<br>잠시 들렀어요.`,'다른 섬에서는 풍경만 천천히 둘러봐요.<br>집중과 설정 변경은 내 섬에서 할 수 있어요.','centered')}<p class="focus-policy">${icon('shield')}구경하는 동안에는 읽기 전용이에요.</p></div>`,footer:action('내 섬으로 돌아가기','return','primary','harbor')+note('내 섬의 기록과 이름은 그대로 보존됩니다')};}
  const renderers={camp,town,board,cabin,harbor,tower,post,result};
  window.GachisupPanels={render:(key,state,buildings)=>state.visiting&&key!=='result'?visit(state,key,buildings):renderers[key](state),meta,presets,friendRows};
})();
