/* 기존 게시판에 전체 멤버 진행률·내기·검사 결과 디자인 상태를 보강한다. */
(() => {
  const {heading:h,note,button:b,input,icon,esc}=GachisupIAView,app=()=>GachisupIAApp;
  function progress(c,q,m){if(!m.public)return {label:'비공개',percent:null};if(!q.participants.includes(m.id))return {label:'참여 전',percent:null};if(!c.api.model.questProgress(q).scheduled)return {label:'오늘은 쉬는 날',percent:null};if(q.category==='SCREEN_TIME')return {label:'측정 연결 대기',percent:null};const today=c.api.model.dateKey(),sessions=c.api.model.allSessions().filter(s=>s.islandId===q.islandId&&s.userId===m.id&&c.api.model.dateKey(s.endedAt)===today&&(!q.placeId||s.source==='local'&&s.questId===q.id));const seconds=sessions.reduce((sum,s)=>{if(q.type==='DURATION')return sum+s.seconds;const start=Date.parse(today+'T'+q.start+':00+09:00'),end=Date.parse(today+'T'+q.end+':00+09:00');return sum+Math.max(0,Math.min(s.endedAt,end)-Math.max(s.startedAt,start))/1000;},0),minutes=Math.floor(seconds/60);return {label:minutes+' / '+q.minutes+'분',percent:Math.min(100,minutes/q.minutes*100)};}
  window.GachisupIABoardDetails=c=>{
    if(c.api.state.selected!=='board')return '';
    const v=c.api.features.ui.view;if(v!==c.ui.previousBoardView){c.ui.previousBoardView=v;c.ui.moderation='unavailable';}
    if(v?.type==='quest'){const q=c.api.model.get().quests.find(q=>q.id===v.id);if(!q)return '';const held=c.data.bets[q.id],hasBet=Object.hasOwn(c.data.bets,q.id),join=document.querySelector('[data-feature=join-quest]');if(join&&hasBet){join.disabled=true;join.textContent='내기 참여 완료 · 예치 중';}
      return `<h3 class="ia-section-title">친구들의 오늘</h3><div class="ia-quest-people">${c.api.model.members(q.islandId).map(m=>{const p=progress(c,q,m);return `<div><span>${esc(m.id==='me'?c.data.profile.name+' · 나':m.name)}</span><small>${p.label}</small>${p.percent!==null?`<i><b style="width:${p.percent}%"></b></i>`:''}</div>`;}).join('')}</div>${note('참여한 친구의 공개 집중만 보여요. 비공개·측정 없음은 0분으로 바꾸지 않아요.')}<h3 class="ia-section-title">작은 약속, 신중한 내기</h3><div class="ia-escrow-info"><span>참가비<b>${q.fee||0} 재화</b></span><span>내 예치 상태<b>${hasBet?held+'개 예치 중':'아직 예치 없음'}</b></span></div>${note(q.fee?'참여 전에 개인 지갑의 재화를 예치해요. 판정이 끝날 때까지 사용할 수 없어요.':'이 퀘스트는 참가비 없이 참여해요.')}<button class="ia-row" data-ia-action="escrow-help">내기와 정산 방식 확인${icon('arrow')}</button>`;
    }
    if(v?.type==='compose'&&v.kind==='quest'){
      const form=document.querySelector('#feature-compose');if(form&&!form.querySelector('[name=fee]')){const draft=c.api.model.get().drafts[c.api.model.get().currentIsland+':quest:new']||{},field=document.createElement('div');field.className='ia-quest-fee';field.innerHTML=input('fee','참가비 · 시연 재화',draft.fee||0,'type="number" min="0" max="100" step="1"')+note('0이면 무료 참여예요. 유료 내기는 시작 전 예치되며, 승자가 없으면 전액 몰수될 수 있어요. 실제 금액·정산은 서버 연결 전입니다.','notice');form.append(field);}return '';
    }
    if(v?.type==='compose'&&v.kind==='share'){
      const state=c.ui.moderation||'unavailable',states={checking:['검사하고 있어요.','확인하는 동안 내용은 초안으로 남아요.'],passed:['검사 통과 화면의 시안','실제 안전 검사가 아니라, 통과한 경우를 확인하는 디자인 예시예요.'],blocked:['이 자료는 게시할 수 없어요.','유해 판정 화면의 시안이에요. 내용을 수정한 뒤 다시 검사해주세요.'],unavailable:['안전 검사를 연결하지 못했어요.','검사할 수 없을 때는 게시하지 않아요. 작성한 텍스트 초안은 남아 있어요.']};
      document.querySelectorAll('[form=feature-compose],[data-feature=publish-preview]').forEach(el=>{el.disabled=state!=='passed';});
      return `<section class="ia-moderation" data-status="${state}" role="status"><span>${icon(state==='passed'?'check':'shield')}</span><div><h3>${states[state][0]}</h3><p>${states[state][1]}</p></div></section><details class="ia-state-preview"><summary>검사 결과 화면 미리보기</summary><label>디자인 시연 상태<select data-ia-moderation>${Object.entries(states).map(([key,[label]])=>`<option value="${key}" ${state===key?'selected':''}>${label}</option>`).join('')}</select></label>${note('이 선택은 실제 검열 결과를 바꾸지 않아요. 통과 시안에서 저장해도 이 기기에만 저장합니다.')}</details>${note('이미지·텍스트: 검사 후 게시 · 오류 시 차단<br>PDF: 자동 검사 불가, 신고로 사후 대응<br>파일당 10MB · 최대 3개 · 보관 90일은 서버 연결 후 적용')}`;
    }
    if(c.api.features.ui.board==='share')return note('이미지·텍스트는 안전 검사 후 게시해요. PDF는 자동 검사 대상이 아니며 신고 기반으로 대응해요. 실제 검사·보관 만료는 서버 연결 전입니다.');
    return '';
  };
  Object.assign(GachisupIAActions,{
    'escrow-help':()=>app().openSheet('escrow',`${h('약속은 가볍게,<br>내기는 신중하게.')}<ol class="ia-escrow-steps"><li><b>참여 전 예치</b><p>참가비를 개인 지갑에서 잠시 보관해요.</p></li><li><b>기록을 확인해 판정</b><p>기기 권한과 데이터 수신이 필요해요. 측정 없음은 성공으로 보지 않아요.</p></li><li><b>성공한 친구에게 분배</b><p>성공한 친구가 없으면 전액 몰수될 수 있어요. 정산은 서버에서 처리해요.</p></li></ol>${note('현재는 화면·예치 시연만 제공합니다. 서버 판정·몰수·분배는 실행하지 않아요.','notice')}${b('확인했어요','close-sheet','','primary')}`,'내기와 정산 방식'),
    'confirm-bet':(id,c)=>{const q=c.api.model.get().quests.find(q=>q.id===id&&q.active&&q.islandId===c.api.model.get().currentIsland);if(!q||q.participants.includes('me'))throw Error('이미 참여했거나 종료된 퀘스트예요.');c.model.bet(q.id,q.fee);c.api.model.joinQuest(q.id);document.querySelector('#ia-sheet').close();c.api.renderPanel();app().enhance();c.api.toast('시연 재화를 예치하고 참여했어요. 실제 정산은 하지 않아요.');}
  });
  document.addEventListener('click',e=>{if(!window.GachisupIAApp)return;const target=e.target.closest('[data-feature=join-quest]');if(!target)return;const c=app().ctx(),q=c.api.model.get().quests.find(q=>q.id===target.dataset.value);if(!q?.fee||q.participants.includes('me'))return;e.preventDefault();e.stopImmediatePropagation();app().openSheet('quest-bet',`${h('참여하기 전에<br>확인해주세요.')}<h3>${esc(q.title)}</h3><dl class="ia-balance-check"><div><dt>내 개인 지갑</dt><dd>${c.data.wallet}</dd></div><div><dt>예치할 참가비</dt><dd>−${q.fee}</dd></div><div><dt>참여 후 사용 가능한 재화</dt><dd>${c.data.wallet>=q.fee?c.data.wallet-q.fee:'부족'}</dd></div></dl>${note('정산 전에는 예치한 재화를 사용할 수 없어요. 승자 0명일 때 전액 몰수 가능성이 있어요. 이 시연에서는 예치만 반영하며 판정·정산은 하지 않아요.','notice')}<div class="ia-two-actions">${b('더 생각할게요','close-sheet','','secondary')}${b('동의하고 참여','confirm-bet',q.id,'primary',c.data.wallet>=q.fee?'':'disabled')}</div>`,'퀘스트 참가비 확인');},true);
  document.addEventListener('input',e=>{if(!window.GachisupIAApp||!e.target.closest('#feature-compose'))return;const c=app().ctx();if(c.api.features.ui.view?.kind!=='share')return;c.ui.moderation='unavailable';document.querySelectorAll('[form=feature-compose],[data-feature=publish-preview]').forEach(el=>el.disabled=true);const box=document.querySelector('.ia-moderation');if(box){box.dataset.status='unavailable';box.querySelector('h3').textContent='내용이 바뀌었어요. 다시 확인해주세요.';box.querySelector('p').textContent='수정한 자료는 검사 전까지 초안으로 남아요.';}const select=document.querySelector('[data-ia-moderation]');if(select)select.value='unavailable';});
  document.addEventListener('change',e=>{if(e.target.matches('[data-ia-moderation]')&&window.GachisupIAApp){app().ui.moderation=e.target.value;app().api.renderPanel();app().enhance();}});
  document.addEventListener('submit',e=>{if(e.target.id!=='feature-compose'||!window.GachisupIAApp)return;const c=app().ctx();if(c.api.features.ui.view?.kind==='share'&&c.ui.moderation!=='passed'){e.preventDefault();e.stopImmediatePropagation();app().error('안전 검사를 통과하기 전에는 게시할 수 없어요. 초안은 그대로 남겨둘게요.');}},true);
})();
