(() => {
  const V=GachisupIAView,{heading:h,note,input,button:b,link,icon,island,cat,prop,esc}=V;
  const amount=x=>Math.abs(Number(x)).toLocaleString('ko-KR');
  const tabs=(items,current,action)=>'<div class="ia-inline-tabs" role="tablist">'+items.map(([id,label])=>b(label,action,id,'',`role="tab" aria-selected="${current===id}"`)).join('')+'</div>';
  function shop(c,kind){
    const list=c.model.products().filter(p=>p.kind===kind),key=kind==='island'?'islandCategory':'personalCategory';c.ui[key]??=kind==='island'?'all':'head';
    const shown=list.filter(p=>kind==='personal'?p.slot===c.ui[key]:c.ui[key]==='all'||(c.ui[key]==='garden'?['garden','flag'].includes(p.id):c.ui[key]==='bench'?['bench','table'].includes(p.id):p.id===c.ui[key]));
    let selected=shown.find(p=>p.id===c.ui.product)||shown[0];c.ui.product=selected.id;
    const owned=c.data.owned.includes(selected.id),active=kind==='island'?c.data.placed.includes(selected.id):c.data.equipped[selected.slot]===selected.id;
    const balance=kind==='island'?c.data.treasury:c.data.wallet;
    const table=selected.id==='table',currentIsland=c.api.model.get().currentIsland,plotKey=c.ui.studyPlot||c.data.studySlots[currentIsland]||'west',point=table?V.studyPlots[plotKey].point:V.decorPositions[selected.id];
    const placement=table?'<fieldset class="ia-placement-options"><legend>놓아볼 자리 · 미리보기</legend>'+Object.entries(V.studyPlots).map(([id,p])=>b(p.name,'study-preview',id,'secondary',`aria-pressed="${plotKey===id}"`)).join('')+'</fieldset>'+note('길과 건물 입구를 비워둔 자리예요. 그림자와 앉는 위치도 함께 옮겨요. 구매 전 미리보기는 저장하지 않아요.')+(owned?link('마을에서 확인하기','plaza','ia-text-link'):''):'';
    const preview=kind==='island'?`<div class="ia-shop-island"><svg viewBox="${table?'410 210 680 455':'0 0 1536 1024'}" role="img" aria-label="${selected.name} 실제 마을 크기 배치 미리보기"><image href="${GachisupBackground.map.src}" width="1536" height="1024"/>${table?`<ellipse cx="${point[0]}" cy="${point[1]+36}" rx="68" ry="26" fill="#405e3625"/><image href="${GachisupActivities.tableAsset}" x="${point[0]-80}" y="${point[1]-80}" width="160" height="160"/>`:`<svg x="${point[0]-40}" y="${point[1]-68}" width="80" height="80" viewBox="0 0 110 110">${prop(selected.art)}</svg>`}</svg></div>`:cat({...c.data.equipped,[selected.slot]:selected.id});
    return {title:kind==='island'?'섬 꾸밈 상점':'고양이 꾸미기',back:'pr1',header:`<span class="ia-wallet">${icon('coin')}${amount(balance)}</span>`,kind:'shop',body:`${kind==='island'?'<div class="ia-shop-layout"><div class="ia-shop-scene">':''}${preview}<p class="ia-try-label">${kind==='island'?esc(c.api.state.island)+'에 미리 놓아보는 중':'미리 입어보는 중 · 실제 착용은 아래 버튼으로'}</p>${kind==='island'?'</div><div class="ia-shop-selection">':''}${kind==='island'?h('우리 섬을 더 따뜻하게.','섬 금고로 구매하고, 모두 함께 누려요.'):''}${placement}${tabs(kind==='island'?[['all','전체'],['bench','쉼터'],['lamp','조명'],['garden','정원']]:[['head','모자'],['face','얼굴'],['neck','목']],c.ui[key],kind==='island'?'island-category':'personal-category')}<div class="ia-product-grid">${shown.map(p=>`<button class="ia-product" data-ia-action="try-product" data-value="${p.id}" aria-pressed="${p.id===selected.id}">${prop(p.art)}<b>${p.name}</b><span>${c.data.owned.includes(p.id)?'보유 중':icon('coin')+' '+p.price}</span></button>`).join('')}</div>${note('재화 명칭·상품 가격은 디자인 시연값이에요. 현금 결제는 발생하지 않아요.')}${kind==='island'?'</div></div>':''}`,footer:`<div class="ia-purchase-summary"><span>${selected.name}<small>${kind==='island'?'섬 금고':'개인 지갑'}${kind==='island'&&c.role!=='OWNER'?' · 그룹장만 구매':''}</small></span><strong>${owned?'보유':selected.price}</strong></div>${owned&&table?b('이 자리에 놓기','place-study',plotKey,'primary',c.role!=='OWNER'?'disabled':'')+(active?b('기본 공동 자리로 돌려놓기','equip','table','ia-text-link',c.role!=='OWNER'?'disabled':''):''):owned?b(active?(kind==='island'?'배치 해제하기':'벗기'):(kind==='island'?'섬에 놓기':'착용하기'),'equip',selected.id,'primary',kind==='island'&&c.role!=='OWNER'?'disabled':''):b(kind==='island'&&c.role!=='OWNER'?'그룹장에게 꾸밈을 제안해요':selected.price+' 재화로 구매하기','purchase-sheet',selected.id,'primary',kind==='island'&&c.role!=='OWNER'?'disabled':'')}`};
  }
  Object.assign(GachisupIAPages,{
    pr1:c=>{const s=c.api.model.stats({scope:'me',period:'WEEK'}),m=Math.floor(s.seconds/60);return {title:'나의 친구',back:'plaza',header:`<button class="ia-header-icon" data-ia-go="po4" aria-label="수신 설정">${icon('settings')}</button>`,body:`<div class="ia-profile-hero">${cat(c.data.equipped)}<h2 tabindex="-1">${esc(c.data.profile.name)}</h2><p>오늘도 나의 속도로.</p>${b('이름 바꾸기','rename-profile','','ia-text-link')}</div><div class="ia-profile-stats"><div><b>${s.streak}<small>일</small></b><span>연속 집중</span></div><div><b>${Math.floor(m/60)}<small>시간</small> ${m%60}<small>분</small></b><span>이번 주</span></div><div><b>${amount(c.data.wallet)}</b><span>내 지갑</span></div></div>${link('고양이 꾸미기<small>나만의 작은 취향을 더해요.</small>','pr2','ia-row','cat')}${link('섬 꾸밈 상점<small>모두의 자리를 더 아늑하게.</small>','pr3','ia-row','town')}${b('나의 집중 기록','my-stats','','ia-row')}<h3 class="ia-section-title">소속된 섬</h3>${c.api.model.get().islands.map(p=>`<button class="ia-row ia-profile-island" data-ia-action="switch-island" data-value="${p.id}">${island()}<span>${esc(p.name)}<small>Lv. ${p.level} · 친구 ${p.members}명</small></span>${icon('arrow')}</button>`).join('')}${note('통계와 잔액은 이 시연의 예시·직접 기록이에요.')}`};},
    pr2:c=>shop(c,'personal'),pr3:c=>shop(c,'island'),
    vh4:c=>{const current=c.api.model.get().currentIsland,all=c.data.ledger.filter(r=>r.kind==='island'&&(r.islandId||'home')===current),rows=all.filter(r=>c.ui.ledger==='income'?r.amount>0:c.ui.ledger==='expense'?r.amount<0:true),income=all.filter(r=>r.amount>0).reduce((n,r)=>n+r.amount,0),expense=-all.filter(r=>r.amount<0).reduce((n,r)=>n+r.amount,0);return {title:'섬 금고',back:'vh1',body:`${h('함께 모은<br><em>시간의 선물</em>','오늘의 집중이, 우리 섬의 풍경이 돼요.')}<div class="ia-treasury-hero">${icon('coin')}<strong>${amount(c.data.treasury)}</strong><span>재화</span></div><div class="ia-treasury-summary"><div><small>기록된 적립</small><b>+${amount(income)}</b></div><div><small>꾸밈에 사용</small><b>−${amount(expense)}</b></div></div>${tabs([['all','전체'],['income','적립'],['expense','사용']],c.ui.ledger,'ledger-tab')}<div class="ia-ledger">${rows.length?rows.map(r=>`<article><span class="ia-ledger-icon">${icon(r.amount>0?'sprout':'town')}</span><div><h3>${esc(r.title)}</h3><p>${esc(r.by)} · ${new Date(r.at).toLocaleDateString('ko-KR')}</p></div><strong class="${r.amount>0?'positive':''}">${r.amount>0?'+':'−'}${amount(Math.abs(r.amount))}</strong></article>`).join(''):`<div class="ia-empty">${icon('leaf')}<h3>아직 ${c.ui.ledger==='expense'?'사용한':'쌓인'} 내역이 없어요.</h3><p>함께 쌓고 꾸미는 과정이 여기에 남아요.</p></div>`}</div>${note('이 섬의 금고만 보여요. 개인 지갑과 다른 섬의 금고는 별도예요.')}`,footer:link('섬 꾸미러 가기','pr3','ia-button primary')};},
    vh3:c=>{const d={...c.data.islandSettings,name:c.api.state.island},readOnly=c.role!=='OWNER';return {title:'섬 설정',back:'vh1',step:readOnly?'그룹원 · 읽기 전용':'그룹장',body:`<div class="ia-settings-hero">${island()}${h(esc(c.api.state.island),'함께 지킬 약속과 친구들을 돌봐요.')}</div><form id="ia-form" data-form="island-settings" novalidate><fieldset ${readOnly?'disabled':''} class="ia-form-fields">${input('name','섬 이름',d.name,'maxlength="16" required')}<label class="ia-field"><span>섬 소개</span><textarea name="description" maxlength="80" rows="2">${esc(d.description)}</textarea></label><label class="ia-radio-line"><input name="public" type="checkbox" ${d.public?'checked':''}><span>공개 검색 허용<small>다른 친구들이 섬 이름으로 찾아올 수 있어요.</small></span></label><label class="ia-radio-line"><input name="approval" type="checkbox" ${d.approval?'checked':''}><span>가입 승인제<small>그룹장이 확인한 뒤 입항해요.</small></span></label></fieldset></form><h3 class="ia-section-title">함께하는 친구들</h3>${link('가입 신청 <small>'+(c.api.model.get().currentIsland==='home'?c.data.applications.filter(a=>a.status==='pending').length:0)+'건 기다리는 중</small>','sh8')}${link('초대 코드 공유','sh7')}${b('그룹장 위임·멤버 관리','manage-members','','ia-row')}${note('그룹장은 다른 친구에게 위임한 뒤 탈퇴할 수 있어요.','notice')}`,footer:readOnly?note('설정 변경과 가입 승인은 그룹장이 할 수 있어요.'):'<button class="ia-button primary" type="submit" form="ia-form">변경 저장하기</button>'};},
    fo4:c=>({title:'잠금화면 디자인 미리보기',back:null,kind:'lockscreen',body:`<div class="ia-lock-wallpaper">${island()}</div><div class="ia-system-clock"><p>9월 9일 수요일</p><strong>9:41</strong></div><section class="ia-live-widget" aria-label="iOS Live Activity 디자인"><div class="ia-live-brand">${icon('sprout')}같이숲</div><div class="ia-live-body"><div><h2>${icon('book')}${esc(c.api.state.session?.tag||c.api.state.activityTag||'독서')} 중</h2><strong id="ia-live-timer">${document.querySelector('#session-timer')?.textContent||'24:18'}</strong></div><div class="ia-live-friends">${Array.from({length:Math.min(3,c.api.model.get().islands.find(p=>p.id===c.api.model.get().currentIsland)?.members||1)},()=>cat()).join('')}</div></div><p>${esc(c.api.state.island)} · ${c.api.state.session?.worldAction==='fishing'?'우리의 부두 · 동료는 연출 예시':Math.min(3,c.api.model.get().islands.find(p=>p.id===c.api.model.get().currentIsland)?.members||1)+'명이 함께해요'}</p><div class="ia-live-progress"><i></i></div></section>${note('시스템 잠금화면이 아닌 HTML 시안이에요.<br>실제 Live Activity는 iOS 앱에서 연결해야 해요.')}`,footer:link('집중 화면으로 돌아가기','fo2','ia-button secondary')})
  });
  window.GachisupIAActions={
    'try-product':(id,c)=>{c.ui.product=id;c.ui.studyPlot=null;GachisupIAApp.render();},
    'study-preview':(id,c)=>{if(!V.studyPlots[id])return;c.ui.studyPlot=id;GachisupIAApp.render();},
    'place-study':(id,c)=>{c.model.placeStudy(id,c.role,c.api.model.get().currentIsland);GachisupIAApp.render();c.api.toast('테이블과 앉는 자리를 함께 옮겼어요.');},
    'personal-category':(id,c)=>{c.ui.personalCategory=id;GachisupIAApp.render();},'island-category':(id,c)=>{c.ui.islandCategory=id;GachisupIAApp.render();},
    'purchase-sheet':(id,c)=>{c.ui.product=id;GachisupIAApp.openSheet('sh9');},
    'confirm-purchase':(id,c)=>{const p=c.model.purchase(id,c.role,c.api.model.get().currentIsland);document.querySelector('#ia-sheet').close();GachisupIAApp.render(p.kind==='island'?'pr3':'pr2');c.api.toast('시연 재화로 구매했어요. 실제 결제는 없어요.');},
    equip:(id,c)=>{c.model.equip(id,c.role,c.api.model.get().currentIsland);GachisupIAApp.render();c.api.toast('꾸밈을 시연에 반영했어요.');},
    'ledger-tab':(id,c)=>{c.ui.ledger=id;GachisupIAApp.render('vh4');},
    'my-stats':(id,c)=>{GachisupIAApp.navigate('vh2');c.api.state.recordTab='me';c.api.renderPanel();},
    'switch-island':(id,c)=>{c.api.model.configure({currentIsland:id,role:c.data.roles[id]||'MEMBER'});c.api.sync();GachisupIAApp.navigate('plaza');},
    'rename-profile':(id,c)=>{GachisupIAApp.openSheet('rename',`<form id="ia-form" data-form="rename" novalidate>${input('name','친구 이름',c.data.profile.name,'maxlength="8" required')}<button type="submit" class="ia-button primary">이름 저장하기</button></form>`,'친구 이름 바꾸기');},
    'manage-members':(id,c)=>{GachisupIAApp.openSheet('members',`<div class="ia-member-management">${c.api.model.members(c.api.model.get().currentIsland).map(m=>`<div class="ia-row"><span>${esc(m.id==='me'?c.data.profile.name:m.name)}<small>${m.id==='me'?(c.role==='OWNER'?'나 · 그룹장':'나'):'함께하는 친구'}</small></span>${m.id!=='me'&&c.role==='OWNER'?b('위임','transfer-sheet',m.id,'secondary'):''}</div>`).join('')}</div>${note('위임·탈퇴는 확인 후 이 시연의 역할에만 반영돼요.')}${b('이 섬에서 나가기','leave-sheet','','secondary')}`,'함께하는 친구들');}
  };
  window.GachisupIAForms={
    rename:(v,c)=>{c.model.profile({name:v.name});document.querySelector('#ia-sheet').close();GachisupIAApp.render('pr1');},
    'island-settings':(v,c)=>{const id=c.api.model.get().currentIsland;if(c.api.model.get().islands.some(p=>p.id!==id&&p.name===v.name.trim()))throw Error('이미 같은 이름의 섬이 있어요.');c.model.settings({...v,approval:v.approval==='on',public:v.public==='on'},c.role,id);c.api.model.rename(id,v.name);c.api.sync();GachisupIAApp.render('vh3');c.api.toast('이 시연의 섬 설정을 저장했어요.');}
  };
})();
