/* 보조 시트. 원본 IA에는 개수만 있어 화면 흐름에서 9종을 도출했다. */
(() => {
  const {heading:h,note,input,button:b,icon,prop,cat,esc}=GachisupIAView,app=()=>GachisupIAApp;
  window.GachisupIASheets={
    sh1:c=>({title:'집중할 동안 쉬어 갈 앱',body:`${h('작은 방해는<br>잠시 멀리.','기기에서 차단할 앱을 고르는 화면의 시연이에요.')}<form id="ia-form" data-form="blocked-apps"><div class="ia-app-picker">${['YouTube','Instagram','TikTok','Safari'].map((name,i)=>`<label><span class="ia-app-icon ia-app-${i}">${name.slice(0,1)}</span><span>${name}</span><input type="checkbox" name="apps" value="${name}" ${c.data.blockedApps.includes(name)?'checked':''}></label>`).join('')}</div>${note('앱 선택은 저장하지만 실제 차단 권한·앱 목록은 미연결이에요. 앱 이식 시 시스템 선택 화면으로 연결해요.','notice')}<button class="ia-button primary" type="submit">선택 저장하기</button></form>`}),
    sh6:c=>{const id=c.ui.friend||'tofu',p=GachisupIAPokeInfo(c,id),m=p.member;return {title:'친구의 작은 하루',body:`<div class="ia-friend-detail">${cat()}<h2>${esc(m?.name||'친구')}</h2><p>${p.private?'기록을 비공개로 간직하고 있어요.':p.focused?'오늘 이 섬에서 함께 집중했어요.':'오늘은 아직 집중 전이에요.'}</p></div>${p.private?note('집중 시간과 사용량을 공개하지 않아요.'):b('공개 집중 기록 보기','friend-stats',id,'secondary')}${b(p.done?'오늘 안부를 남겼어요':p.focused?'오늘 함께한 친구':'콕, 안부 남기기','poke',id,'primary',p.eligible?'':'disabled')}${note('안부는 친구별 하루 한 번만 남길 수 있어요.')}`};},
    sh7:c=>{const id=c.api.model.get().currentIsland,p=c.model.places().find(p=>p.id===id)||c.data.created,code=p?.code||'NEUTI1';return {title:'우리 섬으로 초대해요',body:`${h('함께할 자리를<br>하나 더.','코드나 링크를 복사해서 친구에게 건네주세요.')}<div class="ia-invite-code"><small>${esc(c.api.state.island)}</small><strong>${esc(code)}</strong><span>초대 코드</span></div>${b('초대 코드 복사','copy-invite','code','primary')}${b('초대 링크 복사','copy-invite','link','secondary')}${note('이 프로토타입의 초대 링크예요. localhost 주소는 같은 기기에서만 열려요. 실제 초대 전송은 하지 않아요.')}`};},
    sh8:c=>({title:'새로운 친구의 입항',body:c.role!=='OWNER'?`${h('그룹장이 확인할 수 있어요.','가입 신청의 확인과 승인은 그룹장 권한이에요.')}${b('닫기','close-sheet','','primary')}`:`${note('느티나무 섬의 가입 신청 예시예요. 승인·거절은 이 기기에만 반영돼요.')}<div class="ia-application-list">${(c.api.model.get().currentIsland==='home'?c.data.applications:[]).map(a=>`<article><h3>${esc(a.name)}</h3><p>${esc(a.message)}</p>${a.status==='pending'?`<div class="ia-two-actions">${b('거절','review-request',a.id+':declined','secondary')}${b('함께하기','review-request',a.id+':approved','primary')}</div>`:`<span class="ia-processed">${a.status==='approved'?'입항을 승인했어요':'신청을 거절했어요'}</span>`}</article>`).join('')||'<div class="ia-empty"><h3>기다리는 신청이 없어요.</h3><p>친구가 찾아오면 이곳에서 만나요.</p></div>'}</div>`}),
    sh9:c=>{const p=c.model.products().find(p=>p.id===c.ui.product)||c.model.products()[0],balance=p.kind==='island'?c.data.treasury:c.data.wallet,enough=balance>=p.price,owned=c.data.owned.includes(p.id),allowed=p.kind==='personal'||c.role==='OWNER';return {title:'작은 취향을 더할까요?',body:`<div class="ia-confirm-product">${prop(p.art)}<h2>${p.name}</h2><p>${p.kind==='island'?'우리 섬이 함께 쓰는 소품':'나의 고양이에게 줄 선물'}</p></div><dl class="ia-balance-check"><div><dt>${p.kind==='island'?'섬 금고':'개인 지갑'}</dt><dd>${balance}</dd></div><div><dt>구매 비용</dt><dd>−${p.price}</dd></div><div><dt>구매 후 남는 재화</dt><dd>${enough?balance-p.price:'부족'}</dd></div></dl>${!allowed?note('섬 금고는 그룹장만 사용할 수 있어요.','notice'):owned?note('이미 가지고 있는 소품이에요. 다시 차감하지 않아요.'):!enough?note((p.price-balance)+'개가 부족해요. 조금 더 집중하고 돌아올까요?','notice'):note('이 시연의 재화만 사용해요. 현금 결제나 실제 지갑 차감은 없어요.')}<div class="ia-two-actions">${b('조금 더 볼게요','close-sheet','','secondary')}${b('구매하기','confirm-purchase',p.id,'primary',enough&&allowed&&!owned?'':'disabled')}</div>`};}
  };
  Object.assign(GachisupIAActions,{
    'friend-stats':(id,c)=>{document.querySelector('#ia-sheet').close();app().navigate('vh2');c.api.features.ui.user=id;c.api.renderPanel();},
    'copy-invite':async(kind,c)=>{const id=c.api.model.get().currentIsland,p=c.model.places().find(p=>p.id===id)||c.data.created,code=p?.code||'NEUTI1',text=kind==='code'?code:new URL('index.html?ia=on2&invite='+encodeURIComponent(code),location.href).href;try{await navigator.clipboard.writeText(text);c.api.toast((kind==='code'?'코드':'링크')+'를 복사했어요.');}catch{app().openSheet('copy',`${input('copy','길게 눌러 복사해주세요',text,'readonly')}${b('닫기','close-sheet','','primary')}`,'직접 복사하기');}},
    'review-request':(value,c)=>{const [id,decision]=value.split(':'),a=c.data.applications.find(a=>a.id===id);if(c.role!=='OWNER'||c.api.model.get().currentIsland!=='home')throw Error('이 신청을 처리할 권한이 없어요.');app().openSheet('review-confirm',`${h(esc(a?.name)+'님의 신청을<br>'+ (decision==='approved'?'승인할까요?':'거절할까요?'))}${note('확인 후 이 기기의 시연 신청 상태에 반영돼요.')}<div class="ia-two-actions">${b('돌아가기','review-back','','secondary')}${b(decision==='approved'?'입항 승인':'신청 거절','confirm-review',value,'primary')}</div>`,'가입 신청 확인');},
    'review-back':()=>app().openSheet('sh8'),
    'confirm-review':(value,c)=>{const [id,decision]=value.split(':');const a=c.model.review(id,decision,c.role);if(decision==='approved')c.api.model.addMember(c.api.model.get().currentIsland,{id:a.id,name:a.name});c.api.sync();app().openSheet('sh8');},
    'transfer-sheet':(id,c)=>{if(c.role!=='OWNER')throw Error('그룹장만 위임할 수 있어요.');const m=c.api.model.members(c.api.model.get().currentIsland).find(m=>m.id===id);if(!m||id==='me')throw Error('위임할 친구를 확인해주세요.');app().openSheet('transfer',`${h(esc(m.name)+'에게<br>섬을 맡길까요?')}${note('확인하면 나는 그룹원이 되고, 섬 설정·금고 지출·가입 승인 권한이 넘어가요. 이 시연의 역할만 바뀝니다.','notice')}<div class="ia-two-actions">${b('취소','close-sheet','','secondary')}${b('그룹장 위임','confirm-transfer',id,'primary')}</div>`,'그룹장 위임');},
    'confirm-transfer':(id,c)=>{c.model.transfer(c.api.model.get().currentIsland,id,c.role);c.api.model.configure({role:'MEMBER'});document.querySelector('#ia-sheet').close();c.api.sync();app().render('vh3');c.api.toast('그룹원 시연으로 바뀌었어요.');},
    'leave-sheet':(id,c)=>{const p=c.api.model.get().islands.find(p=>p.id===c.api.model.get().currentIsland),needs=c.role==='OWNER'&&p.members>1;app().openSheet('leave',`${h(needs?'먼저 섬을<br>맡겨주세요.':p.members===1?'마지막 친구가<br>떠나면 섬이 닫혀요.':'이 섬에서<br>나갈까요?')}${note(needs?'다른 친구에게 그룹장을 위임한 뒤 나갈 수 있어요.':'이 시연의 소속에서 빠져요. 내 개인 집중 기록과 지갑은 남아요. 실제 서버의 섬을 삭제하지 않아요.','notice')}${b(needs?'친구 관리로 돌아가기':'취소',needs?'manage-members':'close-sheet','','secondary')}${needs?'':b('확인하고 나가기','confirm-leave',p.id,'primary')}`,'섬에서 나가기');},
    'confirm-leave':(id,c)=>{const p=c.api.model.get().islands.find(p=>p.id===id);if(!p)throw Error('이미 떠난 섬이에요.');c.model.leave(id,c.role,p.members);c.api.model.leaveIsland(id);document.querySelector('#ia-sheet').close();if(c.api.model.get().islands.length){c.api.sync();app().navigate('hb1');}else{app().ui.onboarding=true;app().navigate('on5');}c.api.toast('시연의 소속에서 나왔어요. 개인 기록은 보관했어요.');}
  });
  Object.assign(GachisupIAForms,{'blocked-apps':(v,c)=>{c.model.apps([...document.querySelectorAll('#ia-sheet input[name=apps]:checked')].map(x=>x.value));app().handlers['close-sheet']();c.api.toast('앱 선택을 저장했어요. 실제 차단은 미연결이에요.');}});
})();
