const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.VILLAGE_URL||(process.env.BASE_URL || 'http://127.0.0.1:4173/').replace(/\/$/, '');
let count=0;const errors=[];
const ok=(v,s)=>{assert.ok(v,s);console.log('✓ '+s);count++;};
(async()=>{const browser=await chromium.launch();try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/rig.html');await page.locator('#character-mount[data-rig-state=ready]').waitFor();
 ok(await page.locator('#character-mount canvas').count()===1,'새 원화 WebGL 리그 준비');
 ok(!await page.locator('script[src="cat-rig.js"]').count(),'거절된 SVG 캐릭터 런타임을 로드하지 않음');
 const time=await page.locator('#character-mount').getAttribute('data-rig-time');await page.waitForTimeout(300);
 ok(time!==await page.locator('#character-mount').getAttribute('data-rig-time'),'실시간 관절 애니메이션 재생');
 await page.locator('#timeline').fill('2');const frozen=await page.locator('#character-mount').getAttribute('data-rig-time');await page.waitForTimeout(150);
 ok(frozen===await page.locator('#character-mount').getAttribute('data-rig-time'),'타임라인 조작 시 일시정지');
 await page.locator('#timeline').fill('4.96');
 ok(Number(await page.locator('#character-mount').getAttribute('data-blink'))>.99,'닫힌 눈 원화로 눈 깜빡임');
 await page.locator('#timeline').fill('5.5');
 ok(Number(await page.locator('#character-mount').getAttribute('data-blink'))===0,'눈 깜빡임 후 승인된 열린 눈 복원');
 await page.locator('#bones-toggle').click();await page.locator('#joint-head').fill('4');
 ok(await page.locator('#character-mount [data-bone]').count()===12,'12개 관절 시각화');
 ok(await page.locator('[data-bone=head]').getAttribute('data-angle')==='4','독립 고개 관절 제어');
 ok((await page.locator('.momo-mesh').getAttribute('d')).length>1000,'실제 변형 메시 표시');
 await page.locator('#reference-toggle').click();
 ok(await page.locator('#character-mount.compare-original').count()===1,'승인 원화 비교 토글');
 await page.locator('#reference-toggle').click();await page.locator('#reset-pose').click();await page.locator('#bones-toggle').click();
 await page.locator('#timeline').fill('10.2');
  ok(Number(await page.locator('.momo-page').getAttribute('opacity'))>.9,'책장 넘김 보조 레이어');
  ok((await page.locator('.momo-page').getAttribute('clip-path')).startsWith('url(#momo-page-window-'),'종이는 표지 앞쪽으로 나오지 않도록 가림 처리');
 const jsonPromise=page.waitForEvent('download');await page.locator('#export-rig').click();const jsonDownload=await jsonPromise;const rig=JSON.parse(await fs.readFile(await jsonDownload.path(),'utf8'));
 ok(rig.format==='gachisup-weighted-mesh'&&Object.keys(rig.bones).length===12,'실제 리그 데이터 JSON 내보내기');
 ok(rig.mesh.indices.length/3===3200&&rig.mesh.vertices.length/2===1681,'3,200개 삼각형과 1,681개 정점');
 ok(rig.mesh.weights.every(row=>Math.abs(row.reduce((a,b)=>a+b,0)-1)<.0001),'각 정점의 스키닝 가중치 합이 1');
 const pngPromise=page.waitForEvent('download');await page.locator('#export-png').click();const pngDownload=await pngPromise;
 const png=await fs.readFile(await pngDownload.path());ok(png.subarray(1,4).toString()==='PNG'&&png.length>100000,'원화와 책장을 합성한 투명 PNG 내보내기');
 await page.locator('[data-clip=nod]').click();ok(await page.locator('[data-clip=nod]').getAttribute('aria-pressed')==='true','고개 끄덕 동작 전환');
 await page.locator('[data-clip=read]').click();
 await page.screenshot({path:path.join(__dirname,'tmp/verification/momo-rig-final-desktop.png'),fullPage:true});
 for(const width of [320,390,768]){await page.setViewportSize({width,height:844});ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),width+'px 작업실 가로 넘침 없음');}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'tmp/verification/momo-rig-final-mobile.png'),fullPage:true});
 await page.goto(base+'/?screen=session');await page.locator('.resident-cat[data-rig-state=ready]').first().waitFor();
  ok(await page.locator('.resident-cat[data-rig-state=ready]').count()===3,'동일 원화 리그를 모닥불의 세 캐릭터에 연결');
  ok(await page.locator('.resident-cat clipPath').evaluateAll(nodes=>new Set(nodes.map(n=>n.id)).size===3),'여러 캐릭터의 책장 가림 영역 ID가 서로 독립적');
 await page.screenshot({path:path.join(__dirname,'tmp/verification/momo-rig-final-village.png')});
 const reduced=await browser.newPage({reducedMotion:'reduce'});await reduced.goto(base+'/rig.html');await reduced.locator('#character-mount[data-rig-state=ready]').waitFor();
 const reducedTime=await reduced.locator('#character-mount').getAttribute('data-rig-time');await reduced.waitForTimeout(200);
 ok(reducedTime===await reduced.locator('#character-mount').getAttribute('data-rig-time'),'동작 줄이기 환경에서 자동 재생 없음');
 await reduced.locator('#play-toggle').click();await reduced.waitForTimeout(180);
 ok(reducedTime!==await reduced.locator('#character-mount').getAttribute('data-rig-time'),'동작 줄이기 환경에서도 명시적 재생 가능');
 await reduced.close();
 const fallback=await browser.newPage();await fallback.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl'?null:get.call(this,type,...args);};});
 await fallback.goto(base+'/rig.html');await fallback.locator('[data-rig-state=fallback]').waitFor();
 ok(await fallback.locator('#export-png').isDisabled(),'WebGL 미지원 시 원화 표시 및 미지원 조작 비활성화');
 await fallback.close();ok(errors.length===0,'브라우저 런타임 오류 없음');
 console.log('\n'+count+'개 검증 통과');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
