const assert=require('node:assert/strict');const api=require('./village-store.js');let count=0;const ok=(v,s)=>{assert.ok(v,s);console.log('✓ '+s);count++;};
const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},model=api.create(storage);const throws=(fn,text)=>assert.throws(fn,new RegExp(text));
ok(api.dateKey(Date.parse('2026-09-08T15:00:00Z'))==='2026-09-09','KST 자정 날짜 경계');
ok(api.periodRange('WEEK',0,Date.parse('2026-09-08T01:00:00Z')).from==='2026-09-07','주간 통계 월요일 시작');
ok(api.periodRange('MONTH',-1,Date.parse('2026-01-08T01:00:00Z')).from==='2025-12-01','월 이동 연도 경계');
throws(()=>model.savePost({kind:'share',islandId:'home',title:'가'.repeat(101),content:'내용'}),'제목');throws(()=>model.savePost({kind:'share',islandId:'home',title:'제목',content:'가'.repeat(5001)}),'내용');ok(true,'제목 100자·본문 5000자 상한');
throws(()=>model.savePost({kind:'notice',islandId:'home',title:' ',content:'hello'}),'제목');ok(true,'공백 제목 거부');
let p=model.savePost({kind:'notice',islandId:'home',title:'새 공지',content:'내용',pinned:true});
ok(model.get().posts.filter(p=>p.islandId==='home'&&p.pinned).length===1,'섬별 고정 공지 최대 한 개');
ok(api.create(storage).get().posts.some(x=>x.id===p),'새 모델에서도 로컬 게시글 복원');
model.savePost({id:p,kind:'notice',islandId:'home',title:'수정',content:'수정된 내용'});ok(model.get().posts.find(x=>x.id===p).content==='수정된 내용','공지 수정');
throws(()=>model.comment(p,'가'.repeat(501)),'500');ok(true,'댓글 500자 상한');
model.comment(p,'댓글');ok(model.get().comments.filter(c=>c.postId===p).length===1,'댓글 저장');model.report(p,'광고');throws(()=>model.report(p,'광고'),'이미');ok(true,'중복 신고 거부');
model.configure({role:'MEMBER'});throws(()=>model.savePost({kind:'notice',islandId:'home',title:'안돼',content:'안돼'}),'그룹장');throws(()=>model.saveQuest({islandId:'home'}),'그룹장');throws(()=>model.deletePost('welcome-home'),'작성자');ok(true,'멤버의 공지·퀘스트 작성과 타인 글 삭제 거부');
const share=model.savePost({kind:'share',islandId:'home',title:'자료',content:'배웠어요'});model.deletePost(share);ok(!model.get().posts.some(p=>p.id===share),'멤버의 자료 작성·자기 글 삭제');
model.configure({role:'OWNER'});model.deletePost(p);ok(!model.get().comments.some(c=>c.postId===p),'글 삭제 시 댓글도 제거');
const q={title:'아침 집중',islandId:'home',category:'FOCUS',type:'TIME_WINDOW',minutes:30,start:'09:00',end:'10:00',days:[1,2,3]};
throws(()=>model.saveQuest({...q,start:'08:90'}),'같은 날');ok(true,'존재하지 않는 시각 08:90 거부');
throws(()=>model.saveQuest({...q,start:'23:00',end:'01:00'}),'같은 날');throws(()=>model.saveQuest({...q,days:[]}),'요일');throws(()=>model.saveQuest({...q,minutes:5}),'6분');throws(()=>model.saveQuest({...q,category:'SCREEN_TIME',minutes:17}),'15분');ok(true,'퀘스트 시간대·반복 요일·카테고리 검증');
const qid=model.saveQuest(q);model.joinQuest(qid);ok(model.get().quests.find(q=>q.id===qid).participants.includes('me'),'퀘스트 참여');model.joinQuest(qid);ok(!model.get().quests.find(q=>q.id===qid).participants.includes('me'),'참여 취소');model.saveQuest({...q,title:'다음 약속'});throws(()=>model.saveQuest(q),'최대 4');ok(true,'활성 퀘스트 최대 4개');model.endQuest(qid);model.saveQuest({...q,title:'빈 자리'});ok(true,'종료 후 새 퀘스트 생성 가능');
for(const scope of ['group','me'])for(const period of ['DAY','WEEK','MONTH']){const s=model.stats({scope,period});ok(s.seconds===s.cells.reduce((n,c)=>n+c.seconds,0)&&s.seconds===s.categories.reduce((n,c)=>n+c.seconds,0)&&s.seconds===s.sessions.reduce((n,x)=>n+x.seconds,0),scope+' '+period+' 합계·차트·과목·세션 일치');ok(s.cells.filter(c=>c.future).every(c=>c.seconds===0&&c.count===0),period+' 미래 날짜 기록 없음');}
const publicStats=model.stats({scope:'group'}),friendSessions=publicStats.sessions.filter(s=>s.userId!=='me');ok(publicStats.sessions.every(s=>s.userId!=='salt')&&publicStats.friendAverage===friendSessions.reduce((n,s)=>n+s.seconds,0)/new Set(friendSessions.map(s=>s.userId)).size,'그룹 세션 비공개 제외·공개 활동 친구 평균 일치');
ok(model.stats({userId:'salt'}).private===true,'친구 비공개 통계 보호');model.configure({samples:false});ok(model.stats({scope:'me'}).seconds===0&&model.stats({scope:'me'}).phone===null,'예시 제외 시 실제 0분과 폰 측정 없음 구분');
const originalNow=Date.now,start=originalNow();model.startSession({started:start,duration:1500,islandId:'home',island:'느티나무 섬',tag:'공부'});throws(()=>model.startSession({}),'진행 중');Date.now=()=>start+65000;const session=model.finishSession();Date.now=originalNow;
ok(session.seconds===65&&session.tag==='공부','실제 경과 시간과 과목으로 세션 저장');ok(model.finishSession()===null&&model.get().sessions.length===1,'중복 종료 시 기록 중복 적립 없음');
model.rename('home','작은 숲');model.configure({currentIsland:'dawn'});ok(model.stats({islandId:'home'}).seconds===65&&model.stats({islandId:'dawn'}).seconds===0&&model.stats({scope:'me'}).seconds===65,'섬 이름 변경·이동 후 섬/개인 기록 귀속 유지');
model.goals(90,180);ok(api.create(storage).get().goals.focus===90,'목표 저장·복원');model.sendLetter('momo',1);ok(model.get().letters[0].preset===1,'프리셋 편지 로컬 저장');model.poke('momo');throws(()=>model.poke('momo'),'이미');ok(true,'콕찌르기 하루 1회');
const broken=api.create({getItem:()=>null,setItem:()=>{throw Error('QuotaExceededError');}});const before=broken.get();throws(()=>broken.savePost({kind:'share',islandId:'home',title:'지키기',content:'지키기'}),'저장 공간');ok(JSON.stringify(broken.get())===JSON.stringify(before),'저장 실패 시 메모리 상태도 변경하지 않음');
const corrupt=api.create({getItem:()=>'{broken',setItem:()=>{throw Error('원본 덮어쓰기 금지');}});ok(!!corrupt.loadError,'손상된 로컬 데이터 자동 덮어쓰기 방지');
console.log('\n'+count+'개 검증 통과');
