const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1040 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => { if (response.status() >= 400 && response.url().startsWith('http://127.0.0.1')) errors.push(`${response.status()} ${response.url()}`); });
  const out = path.join(__dirname,'tmp/verification');
  fs.mkdirSync(out,{recursive:true});
  await page.goto(((process.env.BASE_URL || 'http://127.0.0.1:4173/').replace(/\/$/, '') + '/'), { waitUntil: 'networkidle' });
  await page.screenshot({ path: path.join(out,'desktop.png'), fullPage:true });
  await page.locator('#app').screenshot({path:path.join(out,'home.png')});
  await page.locator('#view .primary-button').click();
  assert.equal(await page.locator('.camp').count(),1);
  await page.locator('[data-duration="50"]').click();
  assert.equal(await page.locator('[data-duration="50"]').getAttribute('aria-pressed'),'true');
  await page.locator('[data-action="start"]').click();
  assert.equal(await page.locator('.session').count(),1);
  await page.locator('.story-nav [data-go="home"]').click();
  assert.equal(await page.locator('.session').count(),1);
  await page.locator('[data-action="finish"]').click();
  assert.equal(await page.locator('dialog').evaluate(e=>e.open),true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.session').count(),1);
  await page.locator('[data-action="finish"]').click();
  await page.locator('[data-action="confirm-finish"]').click();
  assert.equal(await page.locator('.result').count(),1);
  assert.match(await page.locator('.receipt').innerText(),/초/);
  await page.locator('#view [data-go="home"]').click();
  await page.locator('.dock [data-go="tower"]').click();
  assert.match(await page.locator('.empty-state').innerText(),/조금 더 자라면/);
  await page.locator('.empty-state [data-go="town"]').click();
  await page.locator('[data-action="rename"]').click();
  await page.locator('#island-name').fill(' ');
  await page.locator('[data-action="save-name"]').click();
  assert.equal(await page.locator('#island-name').getAttribute('aria-invalid'),'true');
  await page.locator('#island-name').fill('우리의 나무');
  await page.locator('[data-action="save-name"]').click();
  assert.match(await page.locator('.island-level').innerText(),/우리의 나무/);
  await page.locator('#view [data-go="home"]').click();
  await page.locator('.dock [data-go="harbor"]').click();
  await page.locator('[data-island="새벽의 서재"]').click();
  assert.match(await page.locator('.island-name').innerText(),/새벽의 서재/);
  await page.locator('.dock [data-go="harbor"]').click();
  await page.locator('[data-action="visit"]').click();
  await page.locator('.dock [data-go="camp"]').click();
  assert.equal(await page.locator('.world').count(),1);
  await page.locator('[data-action="return"]').click();
  await page.locator('.dock [data-go="cabin"]').click();
  await page.locator('[data-tab="me"]').click();
  assert.equal(await page.locator('[data-tab="me"]').getAttribute('aria-selected'),'true');
  await page.keyboard.press('ArrowLeft');
  assert.equal(await page.locator('[data-tab="group"]').getAttribute('aria-selected'),'true');
  for (const screen of ['home','camp','session','result','town','board','cabin','harbor','tower']) {
    await page.goto(`http://127.0.0.1:4173/?embed=1&screen=${screen}`);
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(out,`${screen}-mobile.png`)});
  }
  const sizes=[];
  for(const width of [320,375,414,768,1366]){
    await page.setViewportSize({width,height:width===1366?768:844});
    await page.goto(((process.env.BASE_URL || 'http://127.0.0.1:4173/').replace(/\/$/, '') + '/'));
    const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
    assert.equal(overflow,false,`가로 넘침: ${width}`);
    sizes.push({width,overflow});
    await page.screenshot({path:path.join(out,`responsive-${width}.png`),fullPage:true});
  }
  await page.goto(((process.env.BASE_URL || 'http://127.0.0.1:4173/').replace(/\/$/, '') + '/?embed=1&art=vector'));
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(out,'svg-home.png')});
  await page.locator('[data-action="zoom"]').click();
  assert.equal(await page.locator('.world.overview').count(),1);
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('.island-camera').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({status:'passed',errors,responsive:sizes,screenshots:out},null,2));
  await browser.close();
})().catch(error=>{console.error(error);process.exitCode=1;});
